config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get :about, to: 'static_pages#about'
  
  get 'sessions/new'
  get :signup, to: 'users#new'
  resources :users

  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  delete :logout, to: 'sessions#destroy'
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    before_save :downcase_email
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    class << self
      
      def digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end
  
      
      def new_token
        SecureRandom.urlsafe_base64
      end
  
    
      def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
      end
  
    
      def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
      end

      def forget
        update_attribute(:remember_digest, nil)
      end
    end
    
    private
      def downcase_email
        self.email = email.downcase
      end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'メールアドレスとパスワードの組み合わせが誤っています'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def terms
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def index
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "クックポストへようこそ"
      redirect_to @user
    else
      render 'new'
    end
end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
      base_title = 'クックポスト'
      if page_title.blank?
        base_title
      else
        "#{page_title} - #{base_title}"
      end
    end
  end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
      end
    
      def current_user
        if session[:user_id]
          @current_user ||= User.find_by(id: session[:user_id])
        end
      end
    
      def logged_in?
        !current_user.nil?
      end

      def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
      end

      def current_user
        if session[:user_id]
          @current_user ||= User.find_by(id: session[:user_id])
        if (user_id = session[:user_id])
          @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
          user = User.find_by(id: user_id)
          if user && user.authenticated?(cookies[:remember_token])
            log_in user
            @current_user = user
          end
        end
      end

      def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
      end
    
      def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
      end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          <small class="block">&copy; 2020 Your Name All Rights Reserved.</small>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <%= link_to(image_tag("header_logo.jpg", :alt => ""), root_url, id: 'logo') %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'クックポストとは？', about_path %></li>
        <% if logged_in? %>
          <li><%= link_to 'ユーザー一覧', users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>

        <% else %>
          <li><%= link_to 'ユーザー登録(無料)', signup_path %></li>
          <li><%= link_to 'ログイン', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="page">
      <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "クックポストとは？") %>
<h1>クックログとは？</h1>

app/views/static_pages/home.html.erb
<center>
  <h1>クックポストへようこそ！</h1>
  <h2>クックポストで日々の献立を記録しませんか？</h2>
  <p>今日のレシピ、もう迷わない！</p>
</center>

app/views/static_pages/terms.html.erb
<% provide(:title, "利用規約") %>
<h1>利用規約</h1>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, "ユーザー登録") %>
<h1>ユーザー登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @user, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class = 'form-group'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', id: 'user_name' %>
      </div>
      <div class = 'form-group'>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', id: 'user_email' %>
      </div>
      <div class = 'form-group'>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', id: 'user_password' %>
      </div>
      <div class = 'form-group'>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control', id: 'user_password_confirmation' %>
      </div>
      <%= f.submit nil, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "プロフィール") %>
<h1>プロフィール</h1>
<%= gravatar_for @user %><br>
<%= @user.id %>, <%= @user.name %>, <%= @user.email %>, <%= @user.sex %><br>
<%= @user.introduction %><br>
<%= @user.created_at %>, <%= @user.updated_at %><br>